# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-07 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ваше имя', max_length=50)),
                ('email', models.EmailField(help_text='Ваш email', max_length=254)),
                ('question', models.CharField(help_text='Вопрос', max_length=1500)),
                ('created_at', models.DateTimeField()),
                ('user_ip', models.CharField(max_length=50)),
            ],
        ),
    ]
