# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20171113_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postfile',
            name='file_description',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='postquestionchoice',
            name='choice_votes',
            field=models.IntegerField(default=0),
        ),
    ]
