# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20171114_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='postfile',
            name='file_description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
