# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20171116_0549'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
