# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_post_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='postfile',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
