# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 01:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20171121_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postquestion',
            name='block',
        ),
        migrations.RemoveField(
            model_name='postquestion',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postquestionchoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='postquestionchoice',
            name='user',
        ),
        migrations.DeleteModel(
            name='PostQuestion',
        ),
        migrations.DeleteModel(
            name='PostQuestionChoice',
        ),
    ]
