# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 02:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20171122_0432'),
    ]

    operations = [
        migrations.AddField(
            model_name='postblock',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
