# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_postblock_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postblock',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
